server:
  error:
    include-message: always
    include-binding-errors: always
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/banking system
    username: postgres
    password: 1000
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: wd213230@gmail.com
    password: zkzkemkufrmbhnmx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

